/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Home`; params?: Router.UnknownInputParams; } | { pathname: `/Screen1`; params?: Router.UnknownInputParams; } | { pathname: `/Screen2`; params?: Router.UnknownInputParams; } | { pathname: `/Screen3`; params?: Router.UnknownInputParams; } | { pathname: `/Screen4`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/Login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/Register`; params?: Router.UnknownInputParams; } | { pathname: `/auth/phoneNumber`; params?: Router.UnknownInputParams; } | { pathname: `/auth/verify`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/Home`; params?: Router.UnknownOutputParams; } | { pathname: `/Screen1`; params?: Router.UnknownOutputParams; } | { pathname: `/Screen2`; params?: Router.UnknownOutputParams; } | { pathname: `/Screen3`; params?: Router.UnknownOutputParams; } | { pathname: `/Screen4`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/Login`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/Register`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/phoneNumber`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/verify`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/Home${`?${string}` | `#${string}` | ''}` | `/Screen1${`?${string}` | `#${string}` | ''}` | `/Screen2${`?${string}` | `#${string}` | ''}` | `/Screen3${`?${string}` | `#${string}` | ''}` | `/Screen4${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/auth/Login${`?${string}` | `#${string}` | ''}` | `/auth/Register${`?${string}` | `#${string}` | ''}` | `/auth/phoneNumber${`?${string}` | `#${string}` | ''}` | `/auth/verify${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Home`; params?: Router.UnknownInputParams; } | { pathname: `/Screen1`; params?: Router.UnknownInputParams; } | { pathname: `/Screen2`; params?: Router.UnknownInputParams; } | { pathname: `/Screen3`; params?: Router.UnknownInputParams; } | { pathname: `/Screen4`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/Login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/Register`; params?: Router.UnknownInputParams; } | { pathname: `/auth/phoneNumber`; params?: Router.UnknownInputParams; } | { pathname: `/auth/verify`; params?: Router.UnknownInputParams; };
    }
  }
}
